name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Only run the latest commit for a PR
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
          dune-cache: true

      - name: Install dependencies
        working-directory: rio
        run: opam install . --deps-only --with-test

      - name: Check format
        working-directory: rio
        run: opam exec -- dune build @fmt
