name: Format

on:
  push:
  pull_request:
    branches: [main]

# Ensures that only the latest commit of a PR can execute the actions.
# Useful for cancelling job when a sequence of commits are quickly added.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - name: Install ocamlformat
        working-directory: dsl_lang
        run: opam install ocamlformat
      - name: Check format 
        working-directory: dsl_lang
        run: |
          [ $(dune fmt 2> >(wc -c)) -ne 0 ] && exit 1