name: Test

on:
  push:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
          cache: true
          dune-cache: true

      - name: Install dependencies
        working-directory: rio
        run: opam install . --deps-only --with-test

      - name: Build
        working-directory: rio
        run: opam exec -- dune build

      - name: Run tests
        working-directory: rio
        run: opam exec -- dune test
